### ISSUE TITLE
links to "RDF/JS Sink Interface" don't explain the sink interface

### ISSUE THREAD

**Issue by gobengo** [rdfjs-base/sink#6]
in the README of this repo and several others there are hyperlinks to "RDF/JS Sink Interface" that go to http://rdf.js.org/ or maybe http://rdf.js.org/#sink-interface but neither of those links explain what the interface is.

(same on this repo https://github.com/rdfjs-base/sink-map)

I like the idea of having a common interface, but it is hard to determine what that is and learn how to use it.

**Comment by bergos** [comment]
I fixed the broken links and updated the readme to be a bit more descriptive.
